name: EKS Deployment and Cleanup

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform: deploy or destroy'
        required: true
        default: 'deploy'
        type: choice
        options:
          - deploy
          - destroy
      cluster_name:
        description: 'EKS cluster name'
        required: true
        default: 'staging-cluster'
        type: string

jobs:
  deploy:
    if: ${{ github.event.inputs.action == 'deploy' }}
    runs-on: ubuntu-latest
    environment: ENV
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT }}:role/GitHubActionsRole
          aws-region: ap-southeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Create backend ECR repository if not exists
        run: |
          aws ecr describe-repositories --repository-names node-backend --region ap-southeast-2 || \
          aws ecr create-repository --repository-name node-backend --region ap-southeast-2

      - name: Create frontend ECR repository if not exists
        run: |
          aws ecr describe-repositories --repository-names react-frontend --region ap-southeast-2 || \
          aws ecr create-repository --repository-name react-frontend --region ap-southeast-2

      - name: Build, tag, and push backend image
        run: |
          cd backend
          docker build -t node-backend .
          docker tag node-backend:latest ${{ vars.AWS_ACCOUNT }}.dkr.ecr.ap-southeast-2.amazonaws.com/node-backend:latest
          docker push ${{ vars.AWS_ACCOUNT }}.dkr.ecr.ap-southeast-2.amazonaws.com/node-backend:latest

      - name: Build, tag, and push frontend image
        run: |
          cd frontend
          docker build -t react-frontend .
          docker tag react-frontend:latest ${{ vars.AWS_ACCOUNT }}.dkr.ecr.ap-southeast-2.amazonaws.com/react-frontend:latest
          docker push ${{ vars.AWS_ACCOUNT }}.dkr.ecr.ap-southeast-2.amazonaws.com/react-frontend:latest

      - name: Install eksctl and kubectl
        run: |
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
          sudo apt-get update && sudo apt-get install -y gettext-base

      - name: Create EKS cluster with eksctl
        env:
          CLUSTER_NAME: ${{ github.event.inputs.cluster_name }}
        run: |
          envsubst < eksctl/cluster.yaml > eksctl/cluster_updated.yaml
          mv eksctl/cluster_updated.yaml eksctl/cluster.yaml

          CLUSTER_REGION="ap-southeast-2"
          if ! eksctl get cluster --name ${CLUSTER_NAME} --region ${CLUSTER_REGION} --output json | jq -e '.[] | select(.Status=="ACTIVE")'; then
            eksctl create cluster -f eksctl/cluster.yaml
          else
            echo "Cluster ${CLUSTER_NAME} already exists in region ${CLUSTER_REGION} and is ACTIVE."
          fi

      - name: Get VPC and Subnet IDs
        run: |
          # Get VPC ID
          VPC_ID=$(aws eks describe-cluster --name ${{ github.event.inputs.cluster_name }} --query 'cluster.resourcesVpcConfig.vpcId' --output text)
          echo "VPC_ID=$VPC_ID" >> $GITHUB_ENV
          
          # Get Subnet IDs
          SUBNET_IDS=$(aws ec2 describe-subnets --filters "Name=vpc-id,Values=$VPC_ID" --query 'Subnets[*].SubnetId' --output text | tr '\t' ',')
          echo "SUBNET_IDS=$SUBNET_IDS" >> $GITHUB_ENV
          
          # Get Security Group ID
          SG_ID=$(aws ec2 describe-security-groups --filters "Name=vpc-id,Values=$VPC_ID" --query 'SecurityGroups[0].GroupId' --output text)
          echo "SG_ID=$SG_ID" >> $GITHUB_ENV

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ github.event.inputs.cluster_name }} --region ap-southeast-2

      - name: Install Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh

      - name: Install AWS Load Balancer Controller
        run: |
          helm repo add eks https://aws.github.io/eks-charts
          helm repo update
          helm upgrade --install aws-load-balancer-controller eks/aws-load-balancer-controller \
            -n kube-system \
            --set clusterName=${{ github.event.inputs.cluster_name }} \
            --set serviceAccount.create=false \
            --set serviceAccount.name=aws-load-balancer-controller

      - name: Wait for AWS Load Balancer Controller to be ready
        run: |
          echo "Waiting for AWS Load Balancer Controller to be ready..."
          kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=aws-load-balancer-controller -n kube-system --timeout=300s
          echo "Waiting for webhook service endpoints..."
          for i in {1..30}; do
            ENDPOINTS=$(kubectl get endpoints aws-load-balancer-webhook-service -n kube-system -o jsonpath='{.subsets[*].addresses[*].ip}' 2>/dev/null || echo "")
            if [ ! -z "$ENDPOINTS" ]; then
              echo "AWS Load Balancer Controller webhook service is ready with endpoints: $ENDPOINTS"
              break
            fi
            echo "Waiting for webhook endpoints... ($i/30)"
            sleep 10
          done
          echo "Verifying webhook service readiness..."
          kubectl get svc aws-load-balancer-webhook-service -n kube-system
          kubectl get endpoints aws-load-balancer-webhook-service -n kube-system

      - name: Create Kubernetes namespace
        run: |
          kubectl create namespace app --dry-run=client -o yaml | kubectl apply -f -

      - name: Create Kubernetes secrets for ECR
        run: |
          kubectl create secret docker-registry ecr-auth \
            --docker-server=${{ vars.AWS_ACCOUNT }}.dkr.ecr.ap-southeast-2.amazonaws.com \
            --docker-username=AWS \
            --docker-password=$(aws ecr get-login-password --region ap-southeast-2) \
            --namespace app \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy backend application
        run: |
          envsubst < k8s/backend.yaml | kubectl apply -f -

      - name: Deploy frontend application
        run: |
          # Create ConfigMap first (in case it's not in the YAML)
          kubectl create configmap nginx-config -n app \
            --from-file=nginx.conf=frontend/nginx.conf \
            --dry-run=client -o yaml | kubectl apply -f -
          
          envsubst < k8s/frontend.yaml | kubectl apply -f -

      - name: Wait for deployments to be ready
        run: |
          # Wait for backend deployment
          echo "Waiting for backend deployment..."
          kubectl rollout status deployment/backend -n app --timeout=600s
          
          # Wait for frontend deployment
          echo "Waiting for frontend deployment..."
          kubectl rollout status deployment/frontend -n app --timeout=600s || {
            echo "Frontend deployment failed, checking status..."
            
            # Debug information
            echo "=== Pod Status ==="
            kubectl get pods -n app -l app=frontend -o wide
            
            echo "=== Deployment Status ==="
            kubectl describe deployment frontend -n app
            
            echo "=== Pod Events ==="
            kubectl describe pods -n app -l app=frontend
            
            echo "=== Pod Logs ==="
            kubectl logs -n app -l app=frontend --tail=50 || echo "No logs available"
            
            echo "=== Previous Pod Logs ==="
            kubectl logs -n app -l app=frontend --previous --tail=50 || echo "No previous logs available"
            
            echo "=== ConfigMap Status ==="
            kubectl get configmap nginx-config -n app -o yaml
            
            echo "=== Image Pull Status ==="
            kubectl get events -n app --field-selector involvedObject.kind=Pod --sort-by='.lastTimestamp'
            
            exit 1
          }

      - name: Wait for ALB to be provisioned
        run: |
          echo "Waiting for ALB to be provisioned..."
          # Wait for up to 5 minutes for the ALB to be provisioned
          for i in {1..30}; do
            ALB_URL=$(kubectl get ingress app-ingress -n app -o jsonpath='{.status.loadBalancer.ingress[0].hostname}' 2>/dev/null)
            if [ ! -z "$ALB_URL" ]; then
              echo "ALB URL: http://$ALB_URL"
              echo "Frontend URL: http://$ALB_URL"
              echo "Backend API URL: http://$ALB_URL/api"
              echo "::set-output name=alb_url::$ALB_URL"
              break
            fi
            echo "Waiting for ALB... ($i/30)"
            sleep 10
          done

  destroy:
    if: ${{ github.event.inputs.action == 'destroy' }}
    runs-on: ubuntu-latest
    environment: ENV
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT }}:role/GitHubActionsRole
          aws-region: ap-southeast-2

      - name: Install eksctl and kubectl
        run: |
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ github.event.inputs.cluster_name }} --region ap-southeast-2

      - name: Force delete unevictable pods
        run: |
          echo "Checking for unevictable pods..."
          # Delete all non-system pods first
          kubectl delete pods --all -n app --force --grace-period=0 || true
          
          # Force delete system pods that might be stuck
          kubectl get pods --all-namespaces --field-selector metadata.namespace!=kube-system -o json | \
          jq -r '.items[] | select(.status.phase != "Succeeded") | "\(.metadata.name) -n \(.metadata.namespace)"' | \
          xargs -r -n 3 kubectl delete pod --force --grace-period=0 || true

      - name: Delete EKS cluster with force
        env:
          CLUSTER_NAME: ${{ github.event.inputs.cluster_name }}
        run: |
          # Update cluster name in eksctl/cluster.yaml
          envsubst < eksctl/cluster.yaml > eksctl/cluster_updated.yaml
          mv eksctl/cluster_updated.yaml eksctl/cluster.yaml
          
          # Force delete cluster without node draining
          eksctl delete cluster -f eksctl/cluster.yaml --force --disable-nodegroup-eviction

      - name: Delete backend ECR repository
        run: |
          aws ecr delete-repository --repository-name node-backend --region ap-southeast-2 --force || true

      - name: Delete frontend ECR repository
        run: |
          aws ecr delete-repository --repository-name react-frontend --region ap-southeast-2 --force || true
