name: Build and Push Docker Images

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: ENV
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT }}:role/GitHubActionsRole
          aws-region: ap-southeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Create backend ECR repository if not exists
        run: |
          aws ecr describe-repositories --repository-names node-backend --region ap-southeast-2 || \
          aws ecr create-repository --repository-name node-backend --region ap-southeast-2

      - name: Create frontend ECR repository if not exists
        run: |
          aws ecr describe-repositories --repository-names react-frontend --region ap-southeast-2 || \
          aws ecr create-repository --repository-name react-frontend --region ap-southeast-2

      - name: Build, tag, and push backend image
        run: |
          cd backend
          docker build -t node-backend .
          docker tag node-backend:latest ${{ vars.AWS_ACCOUNT }}.dkr.ecr.ap-southeast-2.amazonaws.com/node-backend:latest
          docker push ${{ vars.AWS_ACCOUNT }}.dkr.ecr.ap-southeast-2.amazonaws.com/node-backend:latest

      - name: Build, tag, and push frontend image
        run: |
          cd frontend
          docker build -t react-frontend .
          docker tag react-frontend:latest ${{ vars.AWS_ACCOUNT }}.dkr.ecr.ap-southeast-2.amazonaws.com/react-frontend:latest
          docker push ${{ vars.AWS_ACCOUNT }}.dkr.ecr.ap-southeast-2.amazonaws.com/react-frontend:latest
